name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: SSH and deploy
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        echo "$SSH_PRIVATE_KEY" > keyfile
        chmod 600 keyfile
        mkdir -p ~/.ssh/known_hosts
        cp known_hosts ~/.ssh/known_hosts
        ssh -T DrizzyOVO@github.com -i keyfile ec2-51-20-55-133.eu-north-1.compute.amazonaws.com "sudo bash ~/deploy.sh"